FROM	node

RUN		apt-get update \
		&& apt-get install -y yarn \
		&& apt-get autoremove \
		&& apt-get autoclean

ONBUILD WORKDIR	/home/app
ONBUILD COPY	app/package*.json ./
ONBUILD RUN		yarn install
ONBUILD COPY	app/ .
