version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/mern-starter
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
